### ISSUE TITLE
How to disable remote video?

### ISSUE THREAD

**Issue by kumaresh-24** [tan-tan-kanarek/mediasoup-server#2]
Is it possible to disable the remote audio and video for e.g consider the case there are three people in the chat room and one of the user is moderator who can disable the audio and video of other two user if the moderator disable the audio or video of one user the  other user cannot able see the video or hear the audio is it possible to do it ??

**Comment by tan-tan-kanarek** [comment]
Do you refer to muting the exported stream (ffmpeg of vlc) or to muting the RTC stream?
As for the exported stream, since I use RTSP that transports the RTP packets, you can pause any of the streams using RTSP protocol, although I didn't implement it it could be done easily.
But if you are talking about the RTC stream, that's a feature request for mediasoup.

**Comment by kumaresh-24** [comment]
can you please tell me how can i stop all the streams using the RTSP protocol.Since i have no idea about the RTSP protocol.Can you provide some examples how can i do that

and when i try to send offer to all user in the room like below
sendOffer() {
let sessionDescription = this.peerconnection.localDescription;
//	this.send(sessionDescription.type, sessionDescription.sdp);
// TODO send offer to all room members
this.sendRoom(sessionDescription.type, sessionDescription.sdp);
}

it throws the error peer already exists.

The user who have joined in the room 1st can be able to see the video of only one user

**Comment by tan-tan-kanarek** [comment]
As for RTSP, what tool do you use that pulls the streams over RTSP? It might have a pause button.
In the code I implement the RTSP request handler [here](https://github.com/tan-tan-kanarek/mediasoup-server/blob/master/server.js#L659) and the actual pause method is [here](https://github.com/tan-tan-kanarek/mediasoup-server/blob/master/server.js#L382), you could call it yourself internally if you want.

As for peer already exists, that's why this line is commented in my code, I didn't resolve it yet.
If you resolve it before me, please open a pull request.

Many thanks for your inputs.

**Comment by tan-tan-kanarek** [comment]
BTW, the pause RTSP handler, although it's always called for either video or audio, I stop today both video and audio, if it's important to you to stop only one of them, please let me know and I'll fix it.
