### ISSUE TITLE
webrtc h264 to rtmp with codec copy

### ISSUE THREAD

**Issue by lelikg** [tan-tan-kanarek/mediasoup-server#20]
Hi, great lib!
I am trying to send the stream to rtmp without doing transcoding. Is that possible?

**Comment by lelikg** [comment]
ping?

**Comment by tan-tan-kanarek** [comment]
Hi @lelikg,
Transcoding on the audio is required in order to send AAC to the RTMP server.
Although no transcoding is needed on the video, I find that FFMPEG fail to sync the audio and the video if only one of them is transcoded, also, I believe that in most cases you prefer to transcode the video as well just to make sure all your input streams follow similar standards such as frame-size, frame-rate, bit-rate and so on.
