### ISSUE TITLE
Server error after connecting

### ISSUE THREAD

**Issue by Bansikov** [tan-tan-kanarek/mediasoup-server#7]
Hello

Server error after connecting over browser:
Executing: cvlc -vvv --play-and-exit --sout-ffmpeg-strict=-2 --audio-desync=-2000 --sout-mux-caching=4096 --sout=#transcode{acodec=mp4a,samplerate=44100}:std{access=file,mux=mp4,dst=/home/listen/mediasoup-server/recordings/zlK_ftraIOcoHOFKAAAB.mp4} rtsp://demoserver.com:5000/zlK_ftraIOcoHOFKAAAB.sdp
PeerConnection [zlK_ftraIOcoHOFKAAAB] closed
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/listen/mediasoup-server/recordings/zlK_ftraIOcoHOFKAAAB.log'

**Comment by tan-tan-kanarek** [comment]
To solve it, either install vlc on your server, or, comment out this line: https://github.com/tan-tan-kanarek/mediasoup-server/blob/master/server.js#L768

**Comment by Bansikov** [comment]
Thanks.
It is possible to convert mediasoup webrtc stream to a mpeg-dash video for HTML5?
If yes, please give me advice for this way.

**Comment by tan-tan-kanarek** [comment]
Do you want it as live stream of for later to show as VOD?

**Comment by Bansikov** [comment]
1. I'm looking for ways to get more browser support for wertc live streams.
Currently its not supported in a lot of browsers IE11, iOS safari and other.
2. But the main idea is to stream lives and reduce server cpu resources.
Currently mediasoup webrtc use lot of CPU for each viewer.

**Comment by tan-tan-kanarek** [comment]
Instead of recording the stream to file, you can stream it as RTMP stream (using ffmpeg) to any RTMP server.
Many RTMP server types support repackaging as MPEG-DASH, including Wowza that requires license.
I implemented it using NGINX with RTMP module and with MPEG-DASH module.
https://github.com/arut/nginx-rtmp-module
https://github.com/arut/nginx-rtmp-module/wiki/Directives#mpeg-dash

BTW, that will cause some latency but will give you HTTP caching, in the server and in CDN.

**Comment by Bansikov** [comment]
Thank you, i'm currently found this way with  nginx-rtmp too, it's seem to be good solution.
So, using your server + nginx-rtmp we have rtmp/mpeg-dash/HLS streams at once, right?

**Comment by tan-tan-kanarek** [comment]
Yes, but note that the both RTC to RTMP and RTMP to MPEG-DASH will cause some latency.
